site_name: José San Martin
site_url: https://joseluissanmartinmelio.github.io/original-site
theme:
  name: material
  palette:
    primary: black
  font:
    text: Montserrat
    code: Roboto mono
extra_css:
 - stylesheets/extra.css