site_name: José San Martin
site_url: https://mydomain.org/mysite
theme:
  name: material
  palette:
    primary: black
  font:
    text: Montserrat
    code: Roboto mono
extra_css:
 - stylesheets/extra.css